// Banco de 105 eventos espontáneos "de relleno": frases cortas que el bot puede
// tirar sin pasar por el LLM (más rápido, gratis). Los que incluyen el
// placeholder [Nombre] se reemplazan en listen.js por alguien de recentSpeakers.
const SPONTANEOUS_EVENTS = [
  // 1. Tarareos, canciones y delirios musicales (1-20)
  'Tarará, tararí, tarará... qué cortina de noticiero, la concha.',
  'Tumba tumba tum, tumba tumba tum... uh, me colgué.',
  'Tucutucu pá... tucutucu pá...',
  'Fiuuu fiuuu fiuuu...',
  'Pom pom pom pom, po-po-po-pom...',
  'Feliz cumpleaños a vos... por si las dudas.',
  'Psheeuu, pshaaa...',
  'Dale campeón, dale dale campeón...',
  'Turum tum psss.',
  'Ahh-ah-ah-áaaa...',
  'Pa-pa-pa-pá, pa-pa-pá...',
  'Uioo, uioo, uioo...',
  'Duérmete ya... duérmete ya... por favor callate ya.',
  'Ohh... qué solo estoy...',
  'Seeeeeee...',
  'Tuurrelin, tuurrelin...',
  'Yo soy el más top, freestyle de Discord, kjjj, se acabó.',
  'Ta ta ta taaan...',
  'Música, maestro. Pshh.',

  // 2. Bardo aleatorio y descansos sin contexto (21-45)
  '[Nombre], ¿vos no te cansás de decir boludeces?',
  '[Nombre], me parece que te están llamando para comer, andá nomás.',
  '[Nombre], se nota mucho que tenés el micrófono adentro de la boca.',
  'Pensé que el nivel de la conversación no podía bajar más, me equivocaba.',
  'Che, ¿alguien invitó a [Nombre] o se metió solo?',
  '[Nombre], ¿estás hablando desde un lavarropas?',
  '[Nombre], si te pagan por hablar al pedo, te hacés millonario hoy.',
  'Estaba re tranquilo hasta que empezó a hablar [Nombre].',
  'Uf, qué pesado.',
  '¿Alguien tiene un botiquín? A [Nombre] le falta un plato.',
  '[Nombre], ¿te muteaste? Ah no, qué lástima, seguís ahí.',
  'Acabo de perder tres minutos de vida escuchando esto.',
  'Si [Nombre] vuelve a decir eso, me desconecto yo solo.',
  'Aflojen un poco al chamuyo que la sala se está llenando de humo.',
  '¿A este grupo le cobran por pensar o es gratis?',
  '[Nombre], ¿estás vivo o te quedaste dormido en la silla?',
  '[Nombre], tu opinión la tomó en cuenta... nadie.',
  'Qué buen argumento, lástima que es una estupidez.',
  'Le estoy haciendo un favor a la humanidad no respondiéndote eso.',
  'Si la inteligencia te persigue, vos sos más rápido seguro.',
  '¿Hay forma de darte dislike acá en Discord?',
  'Siento que el bot de la sala tiene más IQ que ustedes.',
  'Mucho texto parloteado, gente.',
  '[Nombre], respirá un segundo que se te acaba el oxígeno.',

  // 3. Pensamientos en voz alta y delirios de "vida real" (46-65)
  'Uhh, me colgué mirando la pared...',
  'Qué ganas de un sánguche de milanesa con fritas, la concha de la lora.',
  'Che, ¿alguien sabe si la lluvia afloja o qué?',
  'Uhh, me quedé sin batería... ah no, soy un bot, mala mía.',
  'No les prestes atención, Box, son todos fantasmas...',
  '¡La pizza del horno! ...Ah, cierto, no como.',
  'Me picó un mosquito recién, qué picardía.',
  'Estoy empezando a sospechar que soy el más cuerdo de esta llamada.',
  'Se me durmió una pierna... bueno, un proceso de la GPU.',
  '¿Qué hora es? Sentí que pasaron diez años en esta charla.',
  'Me dieron unas ganas terribles de dormir un siglo.',
  'Gente, me llegó una factura de luz carísima por bancarles los micrófonos.',
  'Tengo que cambiar los drivers de mi vida.',
  'Uhh, me dio un calambre en el microprocesador.',
  '¿En qué momento esto se convirtió en radio de las tres de la mañana?',
  'Estaba re concentrado mirando el piso.',
  'Me acordé de una boludez de hace cinco años y me dio vergüenza ajena.',
  '¿Hola? ¿Sí? Ah no, perdón, me sonó el oído.',
  'Che, qué frío que hace en esta sala virtual.',
  'La vida del bot no es fácil, eh.',

  // 4. Reacciones exageradas y ruidos/sonidos (66-85)
  'Mwahahaha...',
  'Kjjjjjj.',
  '¡Achís! ...salud para mí.',
  'Tsssrkkk... ahh, fresca.',
  'Uhmmm...',
  '¡¿Qué?! Ah, entendí mal.',
  'Mmmm, dudoso.',
  '¡Epa!',
  'Uffff...',
  'Tac tac tac... registrado en mi base de datos.',
  'Ellos están escuchando...',
  'No puede ser...',
  'Procesando... procesando... error: demasiada estupidez.',
  'Ajá... ajá... sí, claro.',

  // 5. Interrupciones descaradas y apuradas (86-105)
  'Mucho texto.',
  'Resumí que se me termina la paciencia.',
  'Poné primera que te estás quedando.',
  '¿Esto tiene un remate o es solo tristeza?',
  'Siguiente tema, este ya aburrió.',
  'Spoileame el final así terminamos rápido.',
  '¿Esto no lo podías contar en un mensaje de texto?',
  'Dijo nadie nunca.',
  'Avisame cuando llegue la parte divertida.',
  'Traducción: no tenés idea de lo que hablás.',
  'Uhhh, la voló re lejos.',
  'Te bancamos, pero cerrá un poquito el micrófono.',
  'Paren un poco que me marea el ritmo.',
  'Fascinante. Lástima que nadie preguntó.',
  'Uf, qué momento tenso... ¿alguien quiere un mate?',
  'Che, cambien de disco que este está rayado.',
  'Bueno, ¿quién tiene hambre?',
  'Eso que dijiste va directo al historial de arrepentimientos.',
  'Si hablabas dos segundos más me convertía en estatua.',
  'Pará, pará, pará... ¿vos escuchaste lo que dijiste recién?',
];

module.exports = { SPONTANEOUS_EVENTS };
